/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.javaDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl1.javaDsl.JavaDslPackage;
import org.xtext.example.mydsl1.javaDsl.NoArrayExpressionWithoutMinus;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>No Array Expression Without Minus</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NoArrayExpressionWithoutMinusImpl extends NoArrayExpressionImpl implements NoArrayExpressionWithoutMinus
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NoArrayExpressionWithoutMinusImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JavaDslPackage.Literals.NO_ARRAY_EXPRESSION_WITHOUT_MINUS;
  }

} //NoArrayExpressionWithoutMinusImpl
