/*
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.ui;

import com.google.inject.Injector;
import compilerJava.ui.internal.CompilerJavaActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CompilerJavaActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CompilerJavaActivator activator = CompilerJavaActivator.getInstance();
		return activator != null ? activator.getInjector(CompilerJavaActivator.ORG_XTEXT_EXAMPLE_MYDSL1_MYDSL) : null;
	}

}
