/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.javaDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.javaDsl.ClassDeclaration#getModifiers <em>Modifiers</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.javaDsl.ClassDeclaration#getClassName <em>Class Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.javaDsl.ClassDeclaration#getExtend <em>Extend</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.javaDsl.ClassDeclaration#getImplements <em>Implements</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.javaDsl.ClassDeclaration#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getClassDeclaration()
 * @model
 * @generated
 */
public interface ClassDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Modifiers</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Modifiers</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modifiers</em>' attribute list.
   * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getClassDeclaration_Modifiers()
   * @model unique="false"
   * @generated
   */
  EList<String> getModifiers();

  /**
   * Returns the value of the '<em><b>Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Class Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Name</em>' attribute.
   * @see #setClassName(String)
   * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getClassDeclaration_ClassName()
   * @model
   * @generated
   */
  String getClassName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.javaDsl.ClassDeclaration#getClassName <em>Class Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Name</em>' attribute.
   * @see #getClassName()
   * @generated
   */
  void setClassName(String value);

  /**
   * Returns the value of the '<em><b>Extend</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Extend</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extend</em>' attribute.
   * @see #setExtend(String)
   * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getClassDeclaration_Extend()
   * @model
   * @generated
   */
  String getExtend();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.javaDsl.ClassDeclaration#getExtend <em>Extend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extend</em>' attribute.
   * @see #getExtend()
   * @generated
   */
  void setExtend(String value);

  /**
   * Returns the value of the '<em><b>Implements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Implements</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Implements</em>' containment reference.
   * @see #setImplements(Interfaces)
   * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getClassDeclaration_Implements()
   * @model containment="true"
   * @generated
   */
  Interfaces getImplements();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.javaDsl.ClassDeclaration#getImplements <em>Implements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Implements</em>' containment reference.
   * @see #getImplements()
   * @generated
   */
  void setImplements(Interfaces value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(ClassBody)
   * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getClassDeclaration_Body()
   * @model containment="true"
   * @generated
   */
  ClassBody getBody();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.javaDsl.ClassDeclaration#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(ClassBody value);

} // ClassDeclaration
