/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.javaDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends ConstantExpression, PrimaryNoNewArray
{
} // Expression
