/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.javaDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For Init</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.javaDsl.ForInit#getExpressions <em>Expressions</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.javaDsl.ForInit#getLocalVariable <em>Local Variable</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getForInit()
 * @model
 * @generated
 */
public interface ForInit extends EObject
{
  /**
   * Returns the value of the '<em><b>Expressions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl1.javaDsl.StatementExpression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' containment reference list.
   * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getForInit_Expressions()
   * @model containment="true"
   * @generated
   */
  EList<StatementExpression> getExpressions();

  /**
   * Returns the value of the '<em><b>Local Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Local Variable</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Local Variable</em>' containment reference.
   * @see #setLocalVariable(LocalVariableDeclaration)
   * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getForInit_LocalVariable()
   * @model containment="true"
   * @generated
   */
  LocalVariableDeclaration getLocalVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.javaDsl.ForInit#getLocalVariable <em>Local Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Local Variable</em>' containment reference.
   * @see #getLocalVariable()
   * @generated
   */
  void setLocalVariable(LocalVariableDeclaration value);

} // ForInit
