/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.javaDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pre Decrement Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getPreDecrementExpression()
 * @model
 * @generated
 */
public interface PreDecrementExpression extends StatementExpression, NoArrayExpression
{
} // PreDecrementExpression
