/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.javaDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary New Array</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.javaDsl.PrimaryNewArray#getArray <em>Array</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getPrimaryNewArray()
 * @model
 * @generated
 */
public interface PrimaryNewArray extends Primary
{
  /**
   * Returns the value of the '<em><b>Array</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Array</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' containment reference.
   * @see #setArray(ArrayCreationExpression)
   * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getPrimaryNewArray_Array()
   * @model containment="true"
   * @generated
   */
  ArrayCreationExpression getArray();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.javaDsl.PrimaryNewArray#getArray <em>Array</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' containment reference.
   * @see #getArray()
   * @generated
   */
  void setArray(ArrayCreationExpression value);

} // PrimaryNewArray
