/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.javaDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Try Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.javaDsl.TryStatement#getTryBody <em>Try Body</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.javaDsl.TryStatement#getParams <em>Params</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.javaDsl.TryStatement#getCatchesBody <em>Catches Body</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.javaDsl.TryStatement#getFinallyBody <em>Finally Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getTryStatement()
 * @model
 * @generated
 */
public interface TryStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Try Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Try Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Try Body</em>' containment reference.
   * @see #setTryBody(Block)
   * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getTryStatement_TryBody()
   * @model containment="true"
   * @generated
   */
  Block getTryBody();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.javaDsl.TryStatement#getTryBody <em>Try Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Try Body</em>' containment reference.
   * @see #getTryBody()
   * @generated
   */
  void setTryBody(Block value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl1.javaDsl.FormalParameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getTryStatement_Params()
   * @model containment="true"
   * @generated
   */
  EList<FormalParameter> getParams();

  /**
   * Returns the value of the '<em><b>Catches Body</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl1.javaDsl.Block}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Catches Body</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Catches Body</em>' containment reference list.
   * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getTryStatement_CatchesBody()
   * @model containment="true"
   * @generated
   */
  EList<Block> getCatchesBody();

  /**
   * Returns the value of the '<em><b>Finally Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Finally Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Finally Body</em>' containment reference.
   * @see #setFinallyBody(Block)
   * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getTryStatement_FinallyBody()
   * @model containment="true"
   * @generated
   */
  Block getFinallyBody();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.javaDsl.TryStatement#getFinallyBody <em>Finally Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Finally Body</em>' containment reference.
   * @see #getFinallyBody()
   * @generated
   */
  void setFinallyBody(Block value);

} // TryStatement
