/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.javaDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Initializer</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl1.javaDsl.JavaDslPackage#getVariableInitializer()
 * @model
 * @generated
 */
public interface VariableInitializer extends EObject
{
} // VariableInitializer
